version: '3.7'
services:
  kafka:
    image: ykkim77/kafka-docker
    container_name: kafka-2.12
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: ykkim77/zookeeper-docker
    container_name: zookeeper-3.4
    hostname: zookeeper
    ports:
      - "2181:2181"
